apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sapp-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sapp
  template:
    metadata:
      labels:
        app: sapp
    spec:
      volumes:
      - name: local-pv
        persistentVolumeClaim:
          claimName: local-pv-claim
      containers:
      - image: lxjsword/sapp:v1
        name: sapp
        ports:
        - containerPort: 8000
          protocol: TCP
        volumeMounts:
        - mountPath: "/home/sapp/pv"
          name: local-pv
        livenessProbe:
          httpGet:
            path: /
            port: 8000
